### ISSUE TITLE
Mirror the official mistralai/Mistral-7B-v0.1 and meta-llama/Llama-2-7b-hf models in train.py as they are gated models

### ISSUE THREAD

**Issue by Nottlespike** [PrimeIntellect-ai/prime-diloco#108]
The official mistralai/Mistral-7B-v0.1 and meta-llama/Llama-2-7b-hf models referenced in train.py are gated models. For a new user, it can be confusing to need to log in using huggingface-cli just to start a training run. It's especially confusing when the traceback mentions Mistral, which in theory has nothing to do with what the user is trying to accomplish.

**Comment by JohannesHa** [comment]
yes good point. do you wanna add `huggingface_cli login` in a quick PR to to the getting started section of the readme?

**Comment by Nottlespike** [comment]
@JohannesHa Created a PR to add section 3 to Getting Started to give the links to request access to the offical models and a brief explanation as to why.
